USE db;

CREATE TABLE IF NOT EXISTS accounts (
    id INT AUTO_INCREMENT,
    name VARCHAR(32) NOT NULL,
    pass VARCHAR(32) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS champions (
    id INT AUTO_INCREMENT,
    account_name VARCHAR(32) NOT NULL,
    name VARCHAR(32) NOT NULL,
    PRIMARY KEY (id)
);